dist: trusty
sudo: required

language: python
python:
  - "3.5"
  - "3.6"

env:
  - SKIP_NETWORK_TESTS=0

addons:
  apt:
    packages:
      - openjdk-7-jdk

install:
    - travis_retry pip install tox
    - jdk_switcher use openjdk7
script:
    - java -version
    - TOX_ENVIRONMENT="py${TRAVIS_PYTHON_VERSION//./}"
    - tox -e "$TOX_ENVIRONMENT"
after_success:
    - if [[ $TOX_ENVIRONMENT == 'py36' ]] ; then tox -e py36-coveralls; else echo "No coverage to do"; fi
