dist: trusty
sudo: required

language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7-dev
      env: TOXENV=py37
  allow_failures:
    - python: 3.7-dev

env:
  - SKIP_NETWORK_TESTS=0

addons:
  apt:
    packages:
      - openjdk-7-jdk

install:
    - travis_retry pip install tox
    - jdk_switcher use openjdk7
script:
    - java -version
    - TOX_ENVIRONMENT="py${TRAVIS_PYTHON_VERSION//./}"
    - tox -e "$TOX_ENVIRONMENT"
after_success:
    - if [[ $TOX_ENVIRONMENT == 'py36' ]] ; then tox -e py36-coveralls; else echo "No coverage to do"; fi
